#
# This file is part of Python Client Library for WLTS.
# Copyright (C) 2020-2021 INPE.
#
# Python Client Library for WLTS is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#
kind: pipeline
name: wlts.py

steps:
- name: build
  image: python:3.7
  commands:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -e .[tests,docs]
  - ./run-tests.sh
  environment:
    WLTS_SERVER_URL: http://brazildatacube.dpi.inpe.br/dev/wlts

- name: coverage
  image: plugins/codecov
  settings:
    files:
    - coverage.xml
    - .coverage
    token:
      from_secret: codecov_token
  when:
    event:
    - push

- name: discord-notify
  image: brazildatacube/bdc-drone-discord
  settings:
    webhook:
      from_secret: discord_webhook
  when:
    status:
      - failure
      - success