language: python

dist: bionic

python:
    - "3.6"

before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install --upgrade wheel

install:
    - pip install -e .[tests,docs]

script:
    - ./run-test.sh


